// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt_xbWIlmojy1egV6EBYe79zIYCP-4P_0',
    appId: '1:496508554243:web:b2ba31a2b98e50f1225236',
    messagingSenderId: '496508554243',
    projectId: 'leitura-avaliada-b88fa',
    authDomain: 'leitura-avaliada-b88fa.firebaseapp.com',
    storageBucket: 'leitura-avaliada-b88fa.firebasestorage.app',
    measurementId: 'G-SH3CXHFLTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8RKvj3lGkIkxHU3rFeRhRcwKr_LONHiQ',
    appId: '1:496508554243:android:989d94f43cca8c8f225236',
    messagingSenderId: '496508554243',
    projectId: 'leitura-avaliada-b88fa',
    storageBucket: 'leitura-avaliada-b88fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS7gPzNdtm2SaBYxY7YFOVrMtiBo_uFk4',
    appId: '1:496508554243:ios:ffac43c0ea7fb866225236',
    messagingSenderId: '496508554243',
    projectId: 'leitura-avaliada-b88fa',
    storageBucket: 'leitura-avaliada-b88fa.firebasestorage.app',
    iosBundleId: 'com.example.leituraAvaliada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS7gPzNdtm2SaBYxY7YFOVrMtiBo_uFk4',
    appId: '1:496508554243:ios:ffac43c0ea7fb866225236',
    messagingSenderId: '496508554243',
    projectId: 'leitura-avaliada-b88fa',
    storageBucket: 'leitura-avaliada-b88fa.firebasestorage.app',
    iosBundleId: 'com.example.leituraAvaliada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt_xbWIlmojy1egV6EBYe79zIYCP-4P_0',
    appId: '1:496508554243:web:fd40216c21e55154225236',
    messagingSenderId: '496508554243',
    projectId: 'leitura-avaliada-b88fa',
    authDomain: 'leitura-avaliada-b88fa.firebaseapp.com',
    storageBucket: 'leitura-avaliada-b88fa.firebasestorage.app',
    measurementId: 'G-WCB405XQMH',
  );
}
